#!/usr/bin/expect

set hordedirectory [lindex $argv 0]


spawn pear run-scripts horde/horde_role


while {1} {
    expect {
        -re {Filesystem location .*}            {send $hordedirectory\r}
        eof                                     {break}
    }
}
